### ISSUE TITLE
debug aws educate credits

### ISSUE THREAD

**Issue by gkiar** [NeuroDataDesign/Syllabus#5]

**Comment by jovo** [comment]
what's the status of this? they still want it.
can we give team captain's access to our account, and tell them to be careful or they will lose access?
i don't want the kids slowed down for some bs reason like we can't get the edu stuff working.

**Comment by gkiar** [comment]
discussed sol'n: we will add team members to our consolidated billing account for aws. If they spend more than ($100?) a month we'll give them the boot. We will make it explicit that AWS is for deployment, not development (unless a particular feature of AWS is required for dev, etc.)
